"""empty message

Revision ID: 24022b155487
Revises: 57f2ea1ef2bd
Create Date: 2020-11-14 20:43:15.666250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24022b155487'
down_revision = '57f2ea1ef2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.Text(length=256), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'description')
    # ### end Alembic commands ###
